import { Session } from "./types";

export const SESSIONS: Session[] = [
  // ---------- PIERNAS ----------
  {
    id: "piernas-inicio",
    name: "Piernas — Primeros Pasos",
    bodyParts: ["piernas"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Sesión suave para activar piernas sin equipo, ideal para empezar.",
    blocks: [
      { exerciseId: "sentadilla-bw", sets: 3, reps: 12, restSeconds: 45 },
      { exerciseId: "puente-gluteo", sets: 3, reps: 15, restSeconds: 45 },
      { exerciseId: "zancada-alterna", sets: 3, reps: 10, restSeconds: 45 },
      { exerciseId: "wall-sit", sets: 3, workSeconds: 20, restSeconds: 40 },
    ],
  },
  {
    id: "piernas-kb-intermedio",
    name: "Piernas con Kettlebell",
    bodyParts: ["piernas"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Fuerza de piernas usando tu kettlebell disponible.",
    blocks: [
      { exerciseId: "sentadilla-goblet", sets: 4, reps: 12, restSeconds: 40 },
      { exerciseId: "zancada-kb", sets: 3, reps: 10, restSeconds: 40 },
      { exerciseId: "peso-muerto-kb", sets: 4, reps: 12, restSeconds: 45 },
      { exerciseId: "step-up-kb", sets: 3, reps: 10, restSeconds: 40 },
    ],
  },
  {
    id: "piernas-fuego",
    name: "Piernas al Límite",
    bodyParts: ["piernas"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Volumen alto para piernas, descansos cortos.",
    blocks: [
      { exerciseId: "sentadilla-sumo-kb", sets: 4, reps: 15, restSeconds: 30 },
      { exerciseId: "zancada-lateral", sets: 4, reps: 12, restSeconds: 30 },
      { exerciseId: "peso-muerto-una-pierna-kb", sets: 3, reps: 10, restSeconds: 35 },
      { exerciseId: "sentadilla-salto", sets: 4, reps: 15, restSeconds: 30 },
      { exerciseId: "wall-sit", sets: 3, workSeconds: 40, restSeconds: 30 },
    ],
  },
  {
    id: "piernas-extremo",
    name: "Piernas Extremo — Sin Piedad",
    bodyParts: ["piernas"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Sesión larga y brutal de piernas, solo para niveles avanzados.",
    blocks: [
      { exerciseId: "sentadilla-goblet", sets: 5, reps: 20, restSeconds: 20 },
      { exerciseId: "sentadilla-salto", sets: 5, reps: 15, restSeconds: 20 },
      { exerciseId: "zancada-kb", sets: 5, reps: 14, restSeconds: 25 },
      { exerciseId: "step-up-kb", sets: 4, reps: 15, restSeconds: 20 },
      { exerciseId: "wall-sit", sets: 4, workSeconds: 60, restSeconds: 20 },
      { exerciseId: "calf-raise", sets: 4, reps: 25, restSeconds: 20 },
    ],
  },
  {
    id: "piernas-express",
    name: "Piernas Express (10 min)",
    bodyParts: ["piernas"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Rápida sesión de piernas para cuando el tiempo apremia.",
    blocks: [
      { exerciseId: "sentadilla-bw", sets: 2, reps: 15, restSeconds: 30 },
      { exerciseId: "zancada-alterna", sets: 2, reps: 12, restSeconds: 30 },
      { exerciseId: "puente-gluteo", sets: 2, reps: 15, restSeconds: 30 },
    ],
  },

  // ---------- ESPALDA ----------
  {
    id: "espalda-inicio",
    name: "Espalda — Base Postural",
    bodyParts: ["espalda"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Ejercicios de activación para mejorar postura y espalda baja.",
    blocks: [
      { exerciseId: "superman", sets: 3, reps: 12, restSeconds: 45 },
      { exerciseId: "perro-pajaro", sets: 3, reps: 10, restSeconds: 40 },
      { exerciseId: "pull-apart-imaginario", sets: 3, reps: 15, restSeconds: 30 },
      { exerciseId: "extension-espalda", sets: 3, reps: 12, restSeconds: 40 },
    ],
  },
  {
    id: "espalda-kb-intermedio",
    name: "Espalda con Kettlebell",
    bodyParts: ["espalda"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Trabajo de tirón y espalda baja usando la kettlebell.",
    blocks: [
      { exerciseId: "remo-kb-una-mano", sets: 4, reps: 12, restSeconds: 40 },
      { exerciseId: "peso-muerto-kb-espalda", sets: 4, reps: 12, restSeconds: 45 },
      { exerciseId: "good-morning-kb", sets: 3, reps: 12, restSeconds: 40 },
      { exerciseId: "superman", sets: 3, reps: 15, restSeconds: 30 },
    ],
  },
  {
    id: "espalda-avanzado",
    name: "Espalda Fuerte",
    bodyParts: ["espalda"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Sesión intensa de espalda combinando tirón y estabilidad.",
    blocks: [
      { exerciseId: "remo-kb-doble", sets: 4, reps: 14, restSeconds: 35 },
      { exerciseId: "renegade-row-kb", sets: 4, reps: 10, restSeconds: 35 },
      { exerciseId: "peso-muerto-kb-espalda", sets: 4, reps: 15, restSeconds: 40 },
      { exerciseId: "swing-kb", sets: 4, reps: 20, restSeconds: 30 },
    ],
  },
  {
    id: "espalda-extremo",
    name: "Espalda Extremo",
    bodyParts: ["espalda"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Volumen alto de tirón, resistencia y explosividad para espalda.",
    blocks: [
      { exerciseId: "swing-kb", sets: 5, reps: 25, restSeconds: 20 },
      { exerciseId: "remo-kb-una-mano", sets: 5, reps: 15, restSeconds: 25 },
      { exerciseId: "renegade-row-kb", sets: 4, reps: 14, restSeconds: 25 },
      { exerciseId: "good-morning-kb", sets: 4, reps: 15, restSeconds: 25 },
      { exerciseId: "superman", sets: 4, reps: 20, restSeconds: 20 },
    ],
  },

  // ---------- PECHO ----------
  {
    id: "pecho-inicio",
    name: "Pecho — Fundamentos",
    bodyParts: ["pecho"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Introducción a las flexiones con progresiones accesibles.",
    blocks: [
      { exerciseId: "flexion-rodillas", sets: 3, reps: 10, restSeconds: 45 },
      { exerciseId: "flexion-amplia", sets: 2, reps: 8, restSeconds: 45 },
      { exerciseId: "plancha", sets: 3, workSeconds: 20, restSeconds: 40 },
    ],
  },
  {
    id: "pecho-kb-intermedio",
    name: "Pecho con Kettlebell",
    bodyParts: ["pecho"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Flexiones y presses con kettlebell para pecho y tríceps.",
    blocks: [
      { exerciseId: "flexion-estandar", sets: 4, reps: 12, restSeconds: 40 },
      { exerciseId: "press-pecho-kb", sets: 4, reps: 12, restSeconds: 40 },
      { exerciseId: "pullover-kb", sets: 3, reps: 12, restSeconds: 40 },
      { exerciseId: "flexion-diamante", sets: 3, reps: 8, restSeconds: 40 },
    ],
  },
  {
    id: "pecho-avanzado",
    name: "Pecho de Hierro",
    bodyParts: ["pecho"],
    difficulty: "avanzado",
    equipment: ["ninguno"],
    description: "Variaciones exigentes de flexión sin equipo.",
    blocks: [
      { exerciseId: "flexion-declinada", sets: 4, reps: 15, restSeconds: 30 },
      { exerciseId: "flexion-diamante", sets: 4, reps: 12, restSeconds: 30 },
      { exerciseId: "flexion-explosiva", sets: 3, reps: 8, restSeconds: 35 },
      { exerciseId: "plancha-desplazamiento", sets: 3, reps: 10, restSeconds: 30 },
    ],
  },
  {
    id: "pecho-extremo",
    name: "Pecho Extremo",
    bodyParts: ["pecho"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Sesión larga de pecho combinando flexiones y kettlebell.",
    blocks: [
      { exerciseId: "flexion-estandar", sets: 5, reps: 20, restSeconds: 20 },
      { exerciseId: "flexion-explosiva", sets: 4, reps: 10, restSeconds: 25 },
      { exerciseId: "press-pecho-kb", sets: 5, reps: 15, restSeconds: 25 },
      { exerciseId: "flexion-diamante", sets: 4, reps: 15, restSeconds: 20 },
      { exerciseId: "pullover-kb", sets: 4, reps: 15, restSeconds: 20 },
    ],
  },

  // ---------- CORE ----------
  {
    id: "core-inicio",
    name: "Core — Activación",
    bodyParts: ["core"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Rutina básica para fortalecer el abdomen y la zona media.",
    blocks: [
      { exerciseId: "plancha", sets: 3, workSeconds: 20, restSeconds: 40 },
      { exerciseId: "dead-bug", sets: 3, reps: 10, restSeconds: 35 },
      { exerciseId: "abdominal-bicicleta", sets: 3, reps: 15, restSeconds: 35 },
    ],
  },
  {
    id: "core-kb-intermedio",
    name: "Core con Kettlebell",
    bodyParts: ["core"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Trabajo de rotación y estabilidad usando la kettlebell.",
    blocks: [
      { exerciseId: "russian-twist-kb", sets: 4, reps: 20, restSeconds: 35 },
      { exerciseId: "kb-halo", sets: 3, reps: 10, restSeconds: 35 },
      { exerciseId: "plancha-lateral", sets: 3, workSeconds: 25, restSeconds: 35 },
      { exerciseId: "v-ups", sets: 3, reps: 12, restSeconds: 35 },
    ],
  },
  {
    id: "core-avanzado",
    name: "Core de Acero",
    bodyParts: ["core"],
    difficulty: "avanzado",
    equipment: ["ninguno"],
    description: "Circuito intenso de abdomen sin descanso entre ejercicios.",
    blocks: [
      { exerciseId: "v-ups", sets: 4, reps: 15, restSeconds: 25 },
      { exerciseId: "mountain-climber", sets: 4, workSeconds: 30, restSeconds: 25 },
      { exerciseId: "plancha-toques-hombro", sets: 4, reps: 20, restSeconds: 25 },
      { exerciseId: "hollow-hold", sets: 3, workSeconds: 30, restSeconds: 25 },
    ],
  },
  {
    id: "core-extremo",
    name: "Core Extremo",
    bodyParts: ["core"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Sesión larga y exigente para un core a prueba de todo.",
    blocks: [
      { exerciseId: "russian-twist-kb", sets: 5, reps: 30, restSeconds: 20 },
      { exerciseId: "v-ups", sets: 5, reps: 18, restSeconds: 20 },
      { exerciseId: "mountain-climber", sets: 4, workSeconds: 40, restSeconds: 20 },
      { exerciseId: "plancha", sets: 4, workSeconds: 45, restSeconds: 20 },
      { exerciseId: "hollow-hold", sets: 4, workSeconds: 35, restSeconds: 20 },
    ],
  },

  // ---------- BRAZOS ----------
  {
    id: "brazos-inicio",
    name: "Brazos — Tonificación",
    bodyParts: ["brazos"],
    difficulty: "principiante",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Sesión ligera para bíceps y tríceps con kettlebell.",
    blocks: [
      { exerciseId: "curl-biceps-kb", sets: 3, reps: 12, restSeconds: 40 },
      { exerciseId: "fondos-triceps", sets: 3, reps: 10, restSeconds: 40 },
      { exerciseId: "arm-circles", sets: 2, workSeconds: 20, restSeconds: 30 },
    ],
  },
  {
    id: "brazos-kb-intermedio",
    name: "Brazos Completos con Kettlebell",
    bodyParts: ["brazos"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Trabajo completo de bíceps, tríceps y hombros.",
    blocks: [
      { exerciseId: "curl-martillo-kb", sets: 4, reps: 12, restSeconds: 35 },
      { exerciseId: "press-hombro-kb", sets: 4, reps: 12, restSeconds: 35 },
      { exerciseId: "triceps-extension-kb", sets: 3, reps: 12, restSeconds: 35 },
      { exerciseId: "elevacion-lateral-kb", sets: 3, reps: 12, restSeconds: 35 },
    ],
  },
  {
    id: "brazos-avanzado",
    name: "Brazos de Acero",
    bodyParts: ["brazos"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Alto volumen para brazos, superserie sin descanso extra.",
    blocks: [
      { exerciseId: "curl-biceps-kb", sets: 4, reps: 15, restSeconds: 25 },
      { exerciseId: "fondos-triceps", sets: 4, reps: 15, restSeconds: 25 },
      { exerciseId: "press-hombro-kb", sets: 4, reps: 14, restSeconds: 25 },
      { exerciseId: "curl-martillo-kb", sets: 3, reps: 15, restSeconds: 25 },
      { exerciseId: "triceps-extension-kb", sets: 3, reps: 15, restSeconds: 25 },
    ],
  },

  // ---------- FULL BODY ----------
  {
    id: "fullbody-inicio",
    name: "Full Body — Introducción",
    bodyParts: ["full-body"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Rutina completa suave para todo el cuerpo, sin equipo.",
    blocks: [
      { exerciseId: "sentadilla-bw", sets: 3, reps: 12, restSeconds: 40 },
      { exerciseId: "flexion-rodillas", sets: 3, reps: 10, restSeconds: 40 },
      { exerciseId: "burpee-sin-salto", sets: 3, reps: 8, restSeconds: 45 },
      { exerciseId: "plancha", sets: 3, workSeconds: 20, restSeconds: 40 },
    ],
  },
  {
    id: "fullbody-kb-intermedio",
    name: "Full Body con Kettlebell",
    bodyParts: ["full-body"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Circuito completo combinando fuerza y potencia con la kettlebell.",
    blocks: [
      { exerciseId: "kb-clean-and-press", sets: 4, reps: 10, restSeconds: 40 },
      { exerciseId: "sentadilla-goblet", sets: 4, reps: 12, restSeconds: 40 },
      { exerciseId: "swing-kb", sets: 4, reps: 15, restSeconds: 35 },
      { exerciseId: "renegade-row-kb", sets: 3, reps: 10, restSeconds: 40 },
    ],
  },
  {
    id: "fullbody-avanzado",
    name: "Full Body Potencia",
    bodyParts: ["full-body"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Combina fuerza, potencia y cardio en un solo circuito.",
    blocks: [
      { exerciseId: "kb-thruster", sets: 4, reps: 12, restSeconds: 30 },
      { exerciseId: "burpee", sets: 4, reps: 10, restSeconds: 35 },
      { exerciseId: "kb-clean", sets: 4, reps: 10, restSeconds: 30 },
      { exerciseId: "kb-turkish-getup", sets: 3, reps: 4, restSeconds: 40 },
      { exerciseId: "swing-kb", sets: 4, reps: 20, restSeconds: 30 },
    ],
  },
  {
    id: "fullbody-extremo",
    name: "Full Body Extremo",
    bodyParts: ["full-body"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "El desafío completo: fuerza, potencia y resistencia sin tregua.",
    blocks: [
      { exerciseId: "kb-snatch", sets: 5, reps: 10, restSeconds: 25 },
      { exerciseId: "burpee", sets: 5, reps: 15, restSeconds: 25 },
      { exerciseId: "kb-thruster", sets: 5, reps: 15, restSeconds: 25 },
      { exerciseId: "renegade-row-kb", sets: 4, reps: 14, restSeconds: 25 },
      { exerciseId: "kb-turkish-getup", sets: 4, reps: 5, restSeconds: 30 },
      { exerciseId: "swing-kb", sets: 5, reps: 25, restSeconds: 20 },
    ],
  },

  // ---------- CARDIO / HIIT ----------
  {
    id: "hiit-inicio",
    name: "HIIT Suave",
    bodyParts: ["cardio"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Introducción al HIIT con intervalos cortos y descansos generosos.",
    blocks: [
      { exerciseId: "jumping-jacks", sets: 4, workSeconds: 20, restSeconds: 40 },
      { exerciseId: "high-knees", sets: 4, workSeconds: 20, restSeconds: 40 },
      { exerciseId: "mountain-climber", sets: 3, workSeconds: 20, restSeconds: 40 },
    ],
  },
  {
    id: "hiit-kb-intermedio",
    name: "HIIT con Kettlebell",
    bodyParts: ["cardio"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Intervalos de cardio potenciados con swings de kettlebell.",
    blocks: [
      { exerciseId: "kb-swing-cardio", sets: 5, workSeconds: 30, restSeconds: 30 },
      { exerciseId: "skater-jump", sets: 4, workSeconds: 25, restSeconds: 30 },
      { exerciseId: "plank-jack", sets: 4, workSeconds: 25, restSeconds: 30 },
    ],
  },
  {
    id: "hiit-avanzado",
    name: "HIIT Intenso",
    bodyParts: ["cardio"],
    difficulty: "avanzado",
    equipment: ["ninguno"],
    description: "Circuito rápido de alta intensidad, descansos cortos.",
    blocks: [
      { exerciseId: "burpee", sets: 5, workSeconds: 30, restSeconds: 20 },
      { exerciseId: "sentadilla-salto-tuck", sets: 5, workSeconds: 25, restSeconds: 20 },
      { exerciseId: "sprint-en-lugar", sets: 5, workSeconds: 30, restSeconds: 20 },
      { exerciseId: "shadow-boxing", sets: 4, workSeconds: 30, restSeconds: 20 },
    ],
  },
  {
    id: "hiit-extremo",
    name: "HIIT Extremo — Sin Descanso",
    bodyParts: ["cardio"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "El circuito más brutal: cardio y kettlebell sin piedad.",
    blocks: [
      { exerciseId: "kb-swing-cardio", sets: 6, workSeconds: 40, restSeconds: 15 },
      { exerciseId: "burpee", sets: 6, workSeconds: 35, restSeconds: 15 },
      { exerciseId: "kb-snatch", sets: 5, workSeconds: 30, restSeconds: 20 },
      { exerciseId: "sentadilla-salto-tuck", sets: 5, workSeconds: 30, restSeconds: 15 },
      { exerciseId: "mountain-climber", sets: 5, workSeconds: 40, restSeconds: 15 },
    ],
  },
  {
    id: "hiit-express",
    name: "HIIT Express (8 min)",
    bodyParts: ["cardio"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Cuando el tiempo es poco pero la intensidad no puede faltar.",
    blocks: [
      { exerciseId: "high-knees", sets: 3, workSeconds: 20, restSeconds: 20 },
      { exerciseId: "burpee-sin-salto", sets: 3, workSeconds: 20, restSeconds: 20 },
      { exerciseId: "plank-jack", sets: 3, workSeconds: 20, restSeconds: 20 },
    ],
  },
];

export function getSessionById(id: string): Session | undefined {
  return SESSIONS.find((s) => s.id === id);
}
