import { Session } from "./types";

export const SESSIONS: Session[] = [
  // ---------- PIERNAS ----------
  {
    id: "piernas-inicio",
    name: "Piernas — Primeros Pasos",
    bodyParts: ["piernas"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Sesión suave para activar piernas sin equipo, ideal para empezar.",
    blocks: [
      { exerciseId: "sentadilla-bw", sets: 3, reps: 12, restSeconds: 45 },
      { exerciseId: "puente-gluteo", sets: 3, reps: 15, restSeconds: 45 },
      { exerciseId: "zancada-alterna", sets: 3, reps: 10, restSeconds: 45 },
      { exerciseId: "wall-sit", sets: 3, workSeconds: 20, restSeconds: 40 },
    ],
  },
  {
    id: "piernas-kb-intermedio",
    name: "Piernas con Kettlebell",
    bodyParts: ["piernas"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Fuerza de piernas usando tu kettlebell disponible.",
    blocks: [
      { exerciseId: "sentadilla-goblet", sets: 4, reps: 12, restSeconds: 40 },
      { exerciseId: "zancada-kb", sets: 3, reps: 10, restSeconds: 40 },
      { exerciseId: "peso-muerto-kb", sets: 4, reps: 12, restSeconds: 45 },
      { exerciseId: "step-up-kb", sets: 3, reps: 10, restSeconds: 40 },
    ],
  },
  {
    id: "piernas-fuego",
    name: "Piernas al Límite",
    bodyParts: ["piernas"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Volumen alto para piernas, descansos cortos.",
    blocks: [
      { exerciseId: "sentadilla-sumo-kb", sets: 4, reps: 15, restSeconds: 30 },
      { exerciseId: "zancada-lateral", sets: 4, reps: 12, restSeconds: 30 },
      { exerciseId: "peso-muerto-una-pierna-kb", sets: 3, reps: 10, restSeconds: 35 },
      { exerciseId: "sentadilla-salto", sets: 4, reps: 15, restSeconds: 30 },
      { exerciseId: "wall-sit", sets: 3, workSeconds: 40, restSeconds: 30 },
    ],
  },
  {
    id: "piernas-extremo",
    name: "Piernas Extremo — Sin Piedad",
    bodyParts: ["piernas"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Sesión larga y brutal de piernas, solo para niveles avanzados.",
    blocks: [
      { exerciseId: "sentadilla-goblet", sets: 5, reps: 20, restSeconds: 20 },
      { exerciseId: "sentadilla-salto", sets: 5, reps: 15, restSeconds: 20 },
      { exerciseId: "zancada-kb", sets: 5, reps: 14, restSeconds: 25 },
      { exerciseId: "step-up-kb", sets: 4, reps: 15, restSeconds: 20 },
      { exerciseId: "wall-sit", sets: 4, workSeconds: 60, restSeconds: 20 },
      { exerciseId: "calf-raise", sets: 4, reps: 25, restSeconds: 20 },
    ],
  },
  {
    id: "piernas-express",
    name: "Piernas Express (10 min)",
    bodyParts: ["piernas"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Rápida sesión de piernas para cuando el tiempo apremia.",
    blocks: [
      { exerciseId: "sentadilla-bw", sets: 2, reps: 15, restSeconds: 30 },
      { exerciseId: "zancada-alterna", sets: 2, reps: 12, restSeconds: 30 },
      { exerciseId: "puente-gluteo", sets: 2, reps: 15, restSeconds: 30 },
    ],
  },

  // ---------- ESPALDA ----------
  {
    id: "espalda-inicio",
    name: "Espalda — Base Postural",
    bodyParts: ["espalda"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Ejercicios de activación para mejorar postura y espalda baja.",
    blocks: [
      { exerciseId: "superman", sets: 3, reps: 12, restSeconds: 45 },
      { exerciseId: "perro-pajaro", sets: 3, reps: 10, restSeconds: 40 },
      { exerciseId: "pull-apart-imaginario", sets: 3, reps: 15, restSeconds: 30 },
      { exerciseId: "extension-espalda", sets: 3, reps: 12, restSeconds: 40 },
    ],
  },
  {
    id: "espalda-kb-intermedio",
    name: "Espalda con Kettlebell",
    bodyParts: ["espalda"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Trabajo de tirón y espalda baja usando la kettlebell.",
    blocks: [
      { exerciseId: "remo-kb-una-mano", sets: 4, reps: 12, restSeconds: 40 },
      { exerciseId: "peso-muerto-kb-espalda", sets: 4, reps: 12, restSeconds: 45 },
      { exerciseId: "good-morning-kb", sets: 3, reps: 12, restSeconds: 40 },
      { exerciseId: "superman", sets: 3, reps: 15, restSeconds: 30 },
    ],
  },
  {
    id: "espalda-avanzado",
    name: "Espalda Fuerte",
    bodyParts: ["espalda"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Sesión intensa de espalda combinando tirón y estabilidad.",
    blocks: [
      { exerciseId: "remo-kb-doble", sets: 4, reps: 14, restSeconds: 35 },
      { exerciseId: "renegade-row-kb", sets: 4, reps: 10, restSeconds: 35 },
      { exerciseId: "peso-muerto-kb-espalda", sets: 4, reps: 15, restSeconds: 40 },
      { exerciseId: "swing-kb", sets: 4, reps: 20, restSeconds: 30 },
    ],
  },
  {
    id: "espalda-extremo",
    name: "Espalda Extremo",
    bodyParts: ["espalda"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Volumen alto de tirón, resistencia y explosividad para espalda.",
    blocks: [
      { exerciseId: "swing-kb", sets: 5, reps: 25, restSeconds: 20 },
      { exerciseId: "remo-kb-una-mano", sets: 5, reps: 15, restSeconds: 25 },
      { exerciseId: "renegade-row-kb", sets: 4, reps: 14, restSeconds: 25 },
      { exerciseId: "good-morning-kb", sets: 4, reps: 15, restSeconds: 25 },
      { exerciseId: "superman", sets: 4, reps: 20, restSeconds: 20 },
    ],
  },

  // ---------- PECHO ----------
  {
    id: "pecho-inicio",
    name: "Pecho — Fundamentos",
    bodyParts: ["pecho"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Introducción a las flexiones con progresiones accesibles.",
    blocks: [
      { exerciseId: "flexion-rodillas", sets: 3, reps: 10, restSeconds: 45 },
      { exerciseId: "flexion-amplia", sets: 2, reps: 8, restSeconds: 45 },
      { exerciseId: "plancha", sets: 3, workSeconds: 20, restSeconds: 40 },
    ],
  },
  {
    id: "pecho-kb-intermedio",
    name: "Pecho con Kettlebell",
    bodyParts: ["pecho"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Flexiones y presses con kettlebell para pecho y tríceps.",
    blocks: [
      { exerciseId: "flexion-estandar", sets: 4, reps: 12, restSeconds: 40 },
      { exerciseId: "press-pecho-kb", sets: 4, reps: 12, restSeconds: 40 },
      { exerciseId: "pullover-kb", sets: 3, reps: 12, restSeconds: 40 },
      { exerciseId: "flexion-diamante", sets: 3, reps: 8, restSeconds: 40 },
    ],
  },
  {
    id: "pecho-avanzado",
    name: "Pecho de Hierro",
    bodyParts: ["pecho"],
    difficulty: "avanzado",
    equipment: ["ninguno"],
    description: "Variaciones exigentes de flexión sin equipo.",
    blocks: [
      { exerciseId: "flexion-declinada", sets: 4, reps: 15, restSeconds: 30 },
      { exerciseId: "flexion-diamante", sets: 4, reps: 12, restSeconds: 30 },
      { exerciseId: "flexion-explosiva", sets: 3, reps: 8, restSeconds: 35 },
      { exerciseId: "plancha-desplazamiento", sets: 3, reps: 10, restSeconds: 30 },
    ],
  },
  {
    id: "pecho-extremo",
    name: "Pecho Extremo",
    bodyParts: ["pecho"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Sesión larga de pecho combinando flexiones y kettlebell.",
    blocks: [
      { exerciseId: "flexion-estandar", sets: 5, reps: 20, restSeconds: 20 },
      { exerciseId: "flexion-explosiva", sets: 4, reps: 10, restSeconds: 25 },
      { exerciseId: "press-pecho-kb", sets: 5, reps: 15, restSeconds: 25 },
      { exerciseId: "flexion-diamante", sets: 4, reps: 15, restSeconds: 20 },
      { exerciseId: "pullover-kb", sets: 4, reps: 15, restSeconds: 20 },
    ],
  },

  // ---------- CORE ----------
  {
    id: "core-inicio",
    name: "Core — Activación",
    bodyParts: ["core"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Rutina básica para fortalecer el abdomen y la zona media.",
    blocks: [
      { exerciseId: "plancha", sets: 3, workSeconds: 20, restSeconds: 40 },
      { exerciseId: "dead-bug", sets: 3, reps: 10, restSeconds: 35 },
      { exerciseId: "abdominal-bicicleta", sets: 3, reps: 15, restSeconds: 35 },
    ],
  },
  {
    id: "core-kb-intermedio",
    name: "Core con Kettlebell",
    bodyParts: ["core"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Trabajo de rotación y estabilidad usando la kettlebell.",
    blocks: [
      { exerciseId: "russian-twist-kb", sets: 4, reps: 20, restSeconds: 35 },
      { exerciseId: "kb-halo", sets: 3, reps: 10, restSeconds: 35 },
      { exerciseId: "plancha-lateral", sets: 3, workSeconds: 25, restSeconds: 35 },
      { exerciseId: "v-ups", sets: 3, reps: 12, restSeconds: 35 },
    ],
  },
  {
    id: "core-avanzado",
    name: "Core de Acero",
    bodyParts: ["core"],
    difficulty: "avanzado",
    equipment: ["ninguno"],
    description: "Circuito intenso de abdomen sin descanso entre ejercicios.",
    blocks: [
      { exerciseId: "v-ups", sets: 4, reps: 15, restSeconds: 25 },
      { exerciseId: "mountain-climber", sets: 4, workSeconds: 30, restSeconds: 25 },
      { exerciseId: "plancha-toques-hombro", sets: 4, reps: 20, restSeconds: 25 },
      { exerciseId: "hollow-hold", sets: 3, workSeconds: 30, restSeconds: 25 },
    ],
  },
  {
    id: "core-extremo",
    name: "Core Extremo",
    bodyParts: ["core"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Sesión larga y exigente para un core a prueba de todo.",
    blocks: [
      { exerciseId: "russian-twist-kb", sets: 5, reps: 30, restSeconds: 20 },
      { exerciseId: "v-ups", sets: 5, reps: 18, restSeconds: 20 },
      { exerciseId: "mountain-climber", sets: 4, workSeconds: 40, restSeconds: 20 },
      { exerciseId: "plancha", sets: 4, workSeconds: 45, restSeconds: 20 },
      { exerciseId: "hollow-hold", sets: 4, workSeconds: 35, restSeconds: 20 },
    ],
  },

  // ---------- BRAZOS ----------
  {
    id: "brazos-inicio",
    name: "Brazos — Tonificación",
    bodyParts: ["brazos"],
    difficulty: "principiante",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Sesión ligera para bíceps y tríceps con kettlebell.",
    blocks: [
      { exerciseId: "curl-biceps-kb", sets: 3, reps: 12, restSeconds: 40 },
      { exerciseId: "fondos-triceps", sets: 3, reps: 10, restSeconds: 40 },
      { exerciseId: "arm-circles", sets: 2, workSeconds: 20, restSeconds: 30 },
    ],
  },
  {
    id: "brazos-kb-intermedio",
    name: "Brazos Completos con Kettlebell",
    bodyParts: ["brazos"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Trabajo completo de bíceps, tríceps y hombros.",
    blocks: [
      { exerciseId: "curl-martillo-kb", sets: 4, reps: 12, restSeconds: 35 },
      { exerciseId: "press-hombro-kb", sets: 4, reps: 12, restSeconds: 35 },
      { exerciseId: "triceps-extension-kb", sets: 3, reps: 12, restSeconds: 35 },
      { exerciseId: "elevacion-lateral-kb", sets: 3, reps: 12, restSeconds: 35 },
    ],
  },
  {
    id: "brazos-avanzado",
    name: "Brazos de Acero",
    bodyParts: ["brazos"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Alto volumen para brazos, superserie sin descanso extra.",
    blocks: [
      { exerciseId: "curl-biceps-kb", sets: 4, reps: 15, restSeconds: 25 },
      { exerciseId: "fondos-triceps", sets: 4, reps: 15, restSeconds: 25 },
      { exerciseId: "press-hombro-kb", sets: 4, reps: 14, restSeconds: 25 },
      { exerciseId: "curl-martillo-kb", sets: 3, reps: 15, restSeconds: 25 },
      { exerciseId: "triceps-extension-kb", sets: 3, reps: 15, restSeconds: 25 },
    ],
  },

  // ---------- FULL BODY ----------
  {
    id: "fullbody-inicio",
    name: "Full Body — Introducción",
    bodyParts: ["full-body"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Rutina completa suave para todo el cuerpo, sin equipo.",
    blocks: [
      { exerciseId: "sentadilla-bw", sets: 3, reps: 12, restSeconds: 40 },
      { exerciseId: "flexion-rodillas", sets: 3, reps: 10, restSeconds: 40 },
      { exerciseId: "burpee-sin-salto", sets: 3, reps: 8, restSeconds: 45 },
      { exerciseId: "plancha", sets: 3, workSeconds: 20, restSeconds: 40 },
    ],
  },
  {
    id: "fullbody-kb-intermedio",
    name: "Full Body con Kettlebell",
    bodyParts: ["full-body"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Circuito completo combinando fuerza y potencia con la kettlebell.",
    blocks: [
      { exerciseId: "kb-clean-and-press", sets: 4, reps: 10, restSeconds: 40 },
      { exerciseId: "sentadilla-goblet", sets: 4, reps: 12, restSeconds: 40 },
      { exerciseId: "swing-kb", sets: 4, reps: 15, restSeconds: 35 },
      { exerciseId: "renegade-row-kb", sets: 3, reps: 10, restSeconds: 40 },
    ],
  },
  {
    id: "fullbody-avanzado",
    name: "Full Body Potencia",
    bodyParts: ["full-body"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Combina fuerza, potencia y cardio en un solo circuito.",
    blocks: [
      { exerciseId: "kb-thruster", sets: 4, reps: 12, restSeconds: 30 },
      { exerciseId: "burpee", sets: 4, reps: 10, restSeconds: 35 },
      { exerciseId: "kb-clean", sets: 4, reps: 10, restSeconds: 30 },
      { exerciseId: "kb-turkish-getup", sets: 3, reps: 4, restSeconds: 40 },
      { exerciseId: "swing-kb", sets: 4, reps: 20, restSeconds: 30 },
    ],
  },
  {
    id: "fullbody-extremo",
    name: "Full Body Extremo",
    bodyParts: ["full-body"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "El desafío completo: fuerza, potencia y resistencia sin tregua.",
    blocks: [
      { exerciseId: "kb-snatch", sets: 5, reps: 10, restSeconds: 25 },
      { exerciseId: "burpee", sets: 5, reps: 15, restSeconds: 25 },
      { exerciseId: "kb-thruster", sets: 5, reps: 15, restSeconds: 25 },
      { exerciseId: "renegade-row-kb", sets: 4, reps: 14, restSeconds: 25 },
      { exerciseId: "kb-turkish-getup", sets: 4, reps: 5, restSeconds: 30 },
      { exerciseId: "swing-kb", sets: 5, reps: 25, restSeconds: 20 },
    ],
  },

  // ---------- CARDIO / HIIT ----------
  {
    id: "hiit-inicio",
    name: "HIIT Suave",
    bodyParts: ["cardio"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Introducción al HIIT con intervalos cortos y descansos generosos.",
    blocks: [
      { exerciseId: "jumping-jacks", sets: 4, workSeconds: 20, restSeconds: 40 },
      { exerciseId: "high-knees", sets: 4, workSeconds: 20, restSeconds: 40 },
      { exerciseId: "mountain-climber", sets: 3, workSeconds: 20, restSeconds: 40 },
    ],
  },
  {
    id: "hiit-kb-intermedio",
    name: "HIIT con Kettlebell",
    bodyParts: ["cardio"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Intervalos de cardio potenciados con swings de kettlebell.",
    blocks: [
      { exerciseId: "kb-swing-cardio", sets: 5, workSeconds: 30, restSeconds: 30 },
      { exerciseId: "skater-jump", sets: 4, workSeconds: 25, restSeconds: 30 },
      { exerciseId: "plank-jack", sets: 4, workSeconds: 25, restSeconds: 30 },
    ],
  },
  {
    id: "hiit-avanzado",
    name: "HIIT Intenso",
    bodyParts: ["cardio"],
    difficulty: "avanzado",
    equipment: ["ninguno"],
    description: "Circuito rápido de alta intensidad, descansos cortos.",
    blocks: [
      { exerciseId: "burpee", sets: 5, workSeconds: 30, restSeconds: 20 },
      { exerciseId: "sentadilla-salto-tuck", sets: 5, workSeconds: 25, restSeconds: 20 },
      { exerciseId: "sprint-en-lugar", sets: 5, workSeconds: 30, restSeconds: 20 },
      { exerciseId: "shadow-boxing", sets: 4, workSeconds: 30, restSeconds: 20 },
    ],
  },
  {
    id: "hiit-extremo",
    name: "HIIT Extremo — Sin Descanso",
    bodyParts: ["cardio"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "El circuito más brutal: cardio y kettlebell sin piedad.",
    blocks: [
      { exerciseId: "kb-swing-cardio", sets: 6, workSeconds: 40, restSeconds: 15 },
      { exerciseId: "burpee", sets: 6, workSeconds: 35, restSeconds: 15 },
      { exerciseId: "kb-snatch", sets: 5, workSeconds: 30, restSeconds: 20 },
      { exerciseId: "sentadilla-salto-tuck", sets: 5, workSeconds: 30, restSeconds: 15 },
      { exerciseId: "mountain-climber", sets: 5, workSeconds: 40, restSeconds: 15 },
    ],
  },
  {
    id: "hiit-express",
    name: "HIIT Express (8 min)",
    bodyParts: ["cardio"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Cuando el tiempo es poco pero la intensidad no puede faltar.",
    blocks: [
      { exerciseId: "high-knees", sets: 3, workSeconds: 20, restSeconds: 20 },
      { exerciseId: "burpee-sin-salto", sets: 3, workSeconds: 20, restSeconds: 20 },
      { exerciseId: "plank-jack", sets: 3, workSeconds: 20, restSeconds: 20 },
    ],
  },

  // ---------- MÁS SESIONES ----------
  {
    id: "brazos-extremo",
    name: "Brazos Extremo",
    bodyParts: ["brazos"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "El límite absoluto para bíceps, tríceps y hombros.",
    blocks: [
      { exerciseId: "curl-biceps-kb", sets: 5, reps: 18, restSeconds: 20 },
      { exerciseId: "press-hombro-kb", sets: 5, reps: 16, restSeconds: 20 },
      { exerciseId: "fondos-triceps", sets: 5, reps: 18, restSeconds: 20 },
      { exerciseId: "curl-martillo-kb", sets: 4, reps: 18, restSeconds: 20 },
      { exerciseId: "triceps-extension-kb", sets: 4, reps: 18, restSeconds: 20 },
      { exerciseId: "elevacion-lateral-kb", sets: 4, reps: 15, restSeconds: 20 },
    ],
  },
  {
    id: "brazos-express",
    name: "Brazos Express (8 min)",
    bodyParts: ["brazos"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Bíceps y tríceps rápidos sin nada de equipo.",
    blocks: [
      { exerciseId: "fondos-triceps", sets: 3, reps: 10, restSeconds: 30 },
      { exerciseId: "arm-circles", sets: 2, workSeconds: 20, restSeconds: 25 },
      { exerciseId: "plancha-arriba-abajo", sets: 3, reps: 8, restSeconds: 30 },
    ],
  },
  {
    id: "core-express",
    name: "Core Express (8 min)",
    bodyParts: ["core"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Zona media activada en poco tiempo.",
    blocks: [
      { exerciseId: "dead-bug", sets: 2, reps: 10, restSeconds: 30 },
      { exerciseId: "plancha", sets: 3, workSeconds: 20, restSeconds: 30 },
      { exerciseId: "abdominal-bicicleta", sets: 2, reps: 15, restSeconds: 30 },
    ],
  },
  {
    id: "espalda-express",
    name: "Espalda Express (10 min)",
    bodyParts: ["espalda"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Activación postural rápida sin equipo.",
    blocks: [
      { exerciseId: "superman", sets: 3, reps: 12, restSeconds: 35 },
      { exerciseId: "perro-pajaro", sets: 2, reps: 10, restSeconds: 35 },
      { exerciseId: "pull-apart-imaginario", sets: 2, reps: 15, restSeconds: 25 },
    ],
  },
  {
    id: "pecho-express",
    name: "Pecho Express (8 min)",
    bodyParts: ["pecho"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Flexiones rápidas para activar el pecho.",
    blocks: [
      { exerciseId: "flexion-rodillas", sets: 3, reps: 10, restSeconds: 35 },
      { exerciseId: "flexion-amplia", sets: 2, reps: 8, restSeconds: 35 },
    ],
  },
  {
    id: "fullbody-express",
    name: "Full Body Express (10 min)",
    bodyParts: ["full-body"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Circuito corto de cuerpo completo sin equipo.",
    blocks: [
      { exerciseId: "burpee-sin-salto", sets: 3, reps: 8, restSeconds: 30 },
      { exerciseId: "mountain-climber", sets: 3, workSeconds: 25, restSeconds: 30 },
      { exerciseId: "sentadilla-bw", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "flexion-rodillas", sets: 3, reps: 10, restSeconds: 30 },
    ],
  },
  {
    id: "piernas-gluteo-intermedio",
    name: "Piernas y Glúteo",
    bodyParts: ["piernas"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Enfocada en glúteo e isquiotibiales, sin equipo.",
    blocks: [
      { exerciseId: "puente-gluteo", sets: 4, reps: 15, restSeconds: 35 },
      { exerciseId: "zancada-lateral", sets: 3, reps: 12, restSeconds: 35 },
      { exerciseId: "sentadilla-bulgara", sets: 3, reps: 10, restSeconds: 40 },
      { exerciseId: "wall-sit", sets: 3, workSeconds: 30, restSeconds: 35 },
    ],
  },
  {
    id: "espalda-hombro-kb-intermedio",
    name: "Espalda y Hombros con Kettlebell",
    bodyParts: ["espalda", "brazos"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Combina tirón de espalda con trabajo de hombro.",
    blocks: [
      { exerciseId: "remo-kb-doble", sets: 4, reps: 12, restSeconds: 35 },
      { exerciseId: "press-hombro-kb", sets: 4, reps: 12, restSeconds: 35 },
      { exerciseId: "elevacion-lateral-kb", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "good-morning-kb", sets: 3, reps: 12, restSeconds: 35 },
    ],
  },
  {
    id: "pecho-brazos-intermedio",
    name: "Pecho y Brazos",
    bodyParts: ["pecho", "brazos"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Combo clásico de empuje para pecho, hombro y tríceps.",
    blocks: [
      { exerciseId: "flexion-estandar", sets: 4, reps: 12, restSeconds: 35 },
      { exerciseId: "press-pecho-kb", sets: 3, reps: 12, restSeconds: 35 },
      { exerciseId: "triceps-extension-kb", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "fondos-triceps", sets: 3, reps: 12, restSeconds: 30 },
    ],
  },
  {
    id: "core-piernas-avanzado",
    name: "Core y Piernas Combinado",
    bodyParts: ["core", "piernas"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Estabilidad de core sumada a fuerza de piernas, sin descanso extra.",
    blocks: [
      { exerciseId: "sentadilla-goblet", sets: 4, reps: 15, restSeconds: 30 },
      { exerciseId: "russian-twist-kb", sets: 4, reps: 20, restSeconds: 25 },
      { exerciseId: "peso-muerto-una-pierna-kb", sets: 3, reps: 10, restSeconds: 30 },
      { exerciseId: "v-ups", sets: 3, reps: 15, restSeconds: 25 },
    ],
  },
  {
    id: "hiit-piernas-avanzado",
    name: "HIIT de Piernas",
    bodyParts: ["cardio", "piernas"],
    difficulty: "avanzado",
    equipment: ["ninguno"],
    description: "Cardio explosivo enfocado en tren inferior.",
    blocks: [
      { exerciseId: "sentadilla-salto", sets: 5, workSeconds: 25, restSeconds: 20 },
      { exerciseId: "skater-jump", sets: 5, workSeconds: 25, restSeconds: 20 },
      { exerciseId: "high-knees", sets: 4, workSeconds: 25, restSeconds: 20 },
      { exerciseId: "zancada-alterna", sets: 4, reps: 16, restSeconds: 25 },
    ],
  },
  {
    id: "fullbody-kb-avanzado-2",
    name: "Full Body Kettlebell Total",
    bodyParts: ["full-body"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Segundo circuito completo de kettlebell, distinto al clásico.",
    blocks: [
      { exerciseId: "kb-snatch", sets: 4, reps: 10, restSeconds: 35 },
      { exerciseId: "sentadilla-sumo-kb", sets: 4, reps: 14, restSeconds: 30 },
      { exerciseId: "renegade-row-kb", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "kb-halo", sets: 3, reps: 10, restSeconds: 30 },
    ],
  },
  {
    id: "movilidad-recuperacion",
    name: "Recuperación Activa",
    bodyParts: ["full-body"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Sesión suave de baja intensidad para días de descanso activo.",
    blocks: [
      { exerciseId: "perro-pajaro", sets: 2, reps: 10, restSeconds: 30 },
      { exerciseId: "puente-gluteo", sets: 2, reps: 12, restSeconds: 30 },
      { exerciseId: "arm-circles", sets: 2, workSeconds: 20, restSeconds: 25 },
      { exerciseId: "wall-sit", sets: 2, workSeconds: 20, restSeconds: 30 },
    ],
  },
  {
    id: "hiit-full-extremo-2",
    name: "HIIT Total — Segunda Ronda",
    bodyParts: ["cardio", "full-body"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Otro circuito extremo, distinto al original, para no repetir siempre lo mismo.",
    blocks: [
      { exerciseId: "kb-thruster", sets: 5, reps: 15, restSeconds: 20 },
      { exerciseId: "burpee", sets: 5, workSeconds: 30, restSeconds: 20 },
      { exerciseId: "kb-swing-una-mano", sets: 5, reps: 18, restSeconds: 20 },
      { exerciseId: "mountain-climber", sets: 4, workSeconds: 35, restSeconds: 20 },
      { exerciseId: "sentadilla-salto-tuck", sets: 4, workSeconds: 25, restSeconds: 20 },
    ],
  },

  // ---------- PORTERO ----------
  {
    id: "portero-reflejos-intermedio",
    name: "Portero — Reflejos y Reacción",
    bodyParts: ["portero"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Trabajo de reacción, pies rápidos y explosividad lateral para portero.",
    blocks: [
      { exerciseId: "portero-posicion-base", sets: 3, workSeconds: 25, restSeconds: 30 },
      { exerciseId: "portero-pies-rapidos", sets: 4, workSeconds: 20, restSeconds: 25 },
      { exerciseId: "portero-reaccion-lateral", sets: 4, reps: 10, restSeconds: 30 },
      { exerciseId: "high-knees", sets: 3, workSeconds: 20, restSeconds: 25 },
    ],
  },
  {
    id: "portero-potencia-avanzado",
    name: "Portero — Potencia y Zambullidas",
    bodyParts: ["portero"],
    difficulty: "avanzado",
    equipment: ["ninguno"],
    description: "Zambullidas, saltos de alcance y explosividad para atajar de todo.",
    blocks: [
      { exerciseId: "portero-zambullida-lateral", sets: 4, reps: 6, restSeconds: 35 },
      { exerciseId: "portero-salto-alcance", sets: 4, reps: 8, restSeconds: 30 },
      { exerciseId: "portero-reaccion-lateral", sets: 4, reps: 12, restSeconds: 25 },
      { exerciseId: "burpee", sets: 3, reps: 10, restSeconds: 30 },
      { exerciseId: "plancha-lateral", sets: 3, workSeconds: 25, restSeconds: 25 },
    ],
  },
  {
    id: "portero-extremo",
    name: "Portero Extremo",
    bodyParts: ["portero"],
    difficulty: "extremo",
    equipment: ["ninguno"],
    description: "Sesión completa de portero: reacción, zambullidas y resistencia al límite.",
    blocks: [
      { exerciseId: "portero-pies-rapidos", sets: 5, workSeconds: 25, restSeconds: 15 },
      { exerciseId: "portero-zambullida-lateral", sets: 5, reps: 8, restSeconds: 25 },
      { exerciseId: "portero-salto-alcance", sets: 5, reps: 10, restSeconds: 20 },
      { exerciseId: "portero-reaccion-lateral", sets: 5, reps: 14, restSeconds: 20 },
      { exerciseId: "burpee", sets: 4, reps: 12, restSeconds: 20 },
    ],
  },

  // ---------- MUAY THAI ----------
  {
    id: "muaythai-condicionamiento-intermedio",
    name: "Muay Thai — Condicionamiento Básico",
    bodyParts: ["muay-thai"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Rodillazos, patadas y golpes al aire para condición y técnica.",
    blocks: [
      { exerciseId: "shadow-boxing", sets: 3, workSeconds: 30, restSeconds: 30 },
      { exerciseId: "rodillazo-alterno", sets: 3, reps: 16, restSeconds: 30 },
      { exerciseId: "patada-frontal-alterna", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "mountain-climber", sets: 3, workSeconds: 20, restSeconds: 25 },
    ],
  },
  {
    id: "muaythai-cadera-avanzado",
    name: "Muay Thai — Piernas y Cadera Explosiva",
    bodyParts: ["muay-thai"],
    difficulty: "avanzado",
    equipment: ["ninguno"],
    description: "Patadas circulares, rodillazos con salto y potencia de cadera.",
    blocks: [
      { exerciseId: "patada-circular-alterna", sets: 4, reps: 14, restSeconds: 30 },
      { exerciseId: "rodillazo-salto", sets: 4, reps: 10, restSeconds: 30 },
      { exerciseId: "muay-thai-clinch-knees", sets: 3, reps: 16, restSeconds: 30 },
      { exerciseId: "skater-jump", sets: 3, workSeconds: 25, restSeconds: 25 },
      { exerciseId: "shadow-boxing", sets: 3, workSeconds: 30, restSeconds: 25 },
    ],
  },
  {
    id: "muaythai-extremo",
    name: "Muay Thai Extremo",
    bodyParts: ["muay-thai"],
    difficulty: "extremo",
    equipment: ["ninguno"],
    description: "Circuito completo de golpes, rodillas y patadas sin descanso.",
    blocks: [
      { exerciseId: "shadow-boxing", sets: 5, workSeconds: 35, restSeconds: 15 },
      { exerciseId: "rodillazo-salto", sets: 5, reps: 12, restSeconds: 20 },
      { exerciseId: "patada-circular-alterna", sets: 5, reps: 16, restSeconds: 20 },
      { exerciseId: "patada-frontal-alterna", sets: 4, reps: 14, restSeconds: 20 },
      { exerciseId: "muay-thai-clinch-knees", sets: 4, reps: 20, restSeconds: 20 },
      { exerciseId: "burpee", sets: 4, reps: 12, restSeconds: 20 },
    ],
  },

  // ---------- MÁS OPCIONES DE CORE / ABDOMEN ----------
  {
    id: "core-isometrico-intermedio",
    name: "Core Isométrico",
    bodyParts: ["core"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Solo sostenes: plancha y variantes, sin una sola repetición dinámica.",
    blocks: [
      { exerciseId: "plancha", sets: 3, workSeconds: 40, restSeconds: 30 },
      { exerciseId: "plancha-lateral", sets: 3, workSeconds: 30, restSeconds: 30 },
      { exerciseId: "hollow-hold", sets: 3, workSeconds: 25, restSeconds: 30 },
      { exerciseId: "plancha-toques-hombro", sets: 3, reps: 16, restSeconds: 30 },
    ],
  },
  {
    id: "core-rotacional-intermedio",
    name: "Core Rotacional",
    bodyParts: ["core"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Enfocada en rotación de torso: oblicuos y estabilidad antirrotación.",
    blocks: [
      { exerciseId: "russian-twist-kb", sets: 4, reps: 20, restSeconds: 30 },
      { exerciseId: "kb-halo", sets: 3, reps: 10, restSeconds: 30 },
      { exerciseId: "renegade-row-kb", sets: 3, reps: 10, restSeconds: 30 },
      { exerciseId: "abdominal-bicicleta", sets: 3, reps: 20, restSeconds: 25 },
    ],
  },
  {
    id: "core-inferior-avanzado",
    name: "Core Bajo (Abdomen Inferior)",
    bodyParts: ["core"],
    difficulty: "avanzado",
    equipment: ["ninguno"],
    description: "Prioriza la elevación de piernas para trabajar la zona baja del abdomen.",
    blocks: [
      { exerciseId: "elevacion-piernas", sets: 4, reps: 15, restSeconds: 30 },
      { exerciseId: "v-ups", sets: 4, reps: 15, restSeconds: 30 },
      { exerciseId: "dead-bug", sets: 3, reps: 12, restSeconds: 25 },
      { exerciseId: "hollow-hold", sets: 3, workSeconds: 30, restSeconds: 30 },
    ],
  },
  {
    id: "core-kb-avanzado",
    name: "Core con Kettlebell — Nivel Avanzado",
    bodyParts: ["core"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Todo el core trabajado exclusivamente con carga de kettlebell.",
    blocks: [
      { exerciseId: "russian-twist-kb", sets: 5, reps: 24, restSeconds: 25 },
      { exerciseId: "kb-halo", sets: 4, reps: 12, restSeconds: 25 },
      { exerciseId: "renegade-row-kb", sets: 4, reps: 12, restSeconds: 25 },
      { exerciseId: "farmer-carry-kb", sets: 3, workSeconds: 30, restSeconds: 30 },
    ],
  },
  {
    id: "core-sit-up-clasico-principiante",
    name: "Core Clásico",
    bodyParts: ["core"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Los básicos de siempre: sit-ups, bicicleta y plancha, sin complicaciones.",
    blocks: [
      { exerciseId: "sit-up", sets: 3, reps: 15, restSeconds: 35 },
      { exerciseId: "abdominal-bicicleta", sets: 3, reps: 16, restSeconds: 35 },
      { exerciseId: "plancha", sets: 3, workSeconds: 25, restSeconds: 35 },
    ],
  },

  // ---------- MÁS VARIEDAD GENERAL ----------
  {
    id: "piernas-unilateral-avanzado",
    name: "Piernas Unilateral",
    bodyParts: ["piernas"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Todo a una pierna: fuerza, equilibrio y estabilidad de cadera.",
    blocks: [
      { exerciseId: "sentadilla-bulgara", sets: 4, reps: 10, restSeconds: 35 },
      { exerciseId: "peso-muerto-una-pierna-kb", sets: 4, reps: 10, restSeconds: 35 },
      { exerciseId: "step-up-kb", sets: 4, reps: 10, restSeconds: 35 },
      { exerciseId: "equilibrio-una-pierna", sets: 3, reps: 8, restSeconds: 30 },
    ],
  },
  {
    id: "brazos-hombros-intermedio",
    name: "Brazos y Hombros Definición",
    bodyParts: ["brazos"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Volumen moderado-alto para definición de brazos y hombros.",
    blocks: [
      { exerciseId: "elevacion-lateral-kb", sets: 4, reps: 15, restSeconds: 30 },
      { exerciseId: "curl-biceps-kb", sets: 4, reps: 15, restSeconds: 30 },
      { exerciseId: "press-hombro-kb", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "triceps-extension-kb", sets: 3, reps: 15, restSeconds: 30 },
    ],
  },
  {
    id: "movilidad-full-body-intermedio",
    name: "Movilidad Full Body",
    bodyParts: ["full-body"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Sesión enfocada en rango de movimiento y control, no en cargar.",
    blocks: [
      { exerciseId: "estiramiento-mundial", sets: 3, reps: 6, restSeconds: 30 },
      { exerciseId: "gato-camello", sets: 2, reps: 10, restSeconds: 25 },
      { exerciseId: "rotacion-toracica", sets: 2, reps: 8, restSeconds: 25 },
      { exerciseId: "movilidad-cadera-90-90", sets: 2, reps: 8, restSeconds: 25 },
      { exerciseId: "circulos-cadera", sets: 2, workSeconds: 20, restSeconds: 20 },
    ],
  },

  // ---------- MÁS PORTERO ----------
  {
    id: "portero-inicio",
    name: "Portero — Primeros Pasos",
    bodyParts: ["portero"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Introducción a la posición base y reacción, ritmo suave.",
    blocks: [
      { exerciseId: "portero-posicion-base", sets: 2, workSeconds: 20, restSeconds: 35 },
      { exerciseId: "portero-pies-rapidos", sets: 3, workSeconds: 15, restSeconds: 30 },
      { exerciseId: "portero-reaccion-lateral", sets: 3, reps: 8, restSeconds: 35 },
    ],
  },
  {
    id: "portero-express",
    name: "Portero Express (10 min)",
    bodyParts: ["portero"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Reacción y explosividad rápida cuando no tienes mucho tiempo.",
    blocks: [
      { exerciseId: "portero-pies-rapidos", sets: 3, workSeconds: 20, restSeconds: 25 },
      { exerciseId: "portero-salto-alcance", sets: 3, reps: 6, restSeconds: 30 },
      { exerciseId: "portero-reaccion-lateral", sets: 3, reps: 10, restSeconds: 25 },
    ],
  },
  {
    id: "portero-core-avanzado",
    name: "Portero — Core y Estabilidad",
    bodyParts: ["portero", "core"],
    difficulty: "avanzado",
    equipment: ["ninguno"],
    description: "El core que necesitas para caer, girar y volver a levantarte rápido.",
    blocks: [
      { exerciseId: "portero-zambullida-lateral", sets: 3, reps: 8, restSeconds: 35 },
      { exerciseId: "hollow-hold", sets: 3, workSeconds: 25, restSeconds: 30 },
      { exerciseId: "plancha-toques-hombro", sets: 3, reps: 16, restSeconds: 30 },
      { exerciseId: "portero-reaccion-lateral", sets: 3, reps: 12, restSeconds: 30 },
    ],
  },

  // ---------- MÁS MUAY THAI ----------
  {
    id: "muaythai-inicio",
    name: "Muay Thai — Primeros Pasos",
    bodyParts: ["muay-thai"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Técnica básica de rodillazos y patadas al aire, sin apuro.",
    blocks: [
      { exerciseId: "shadow-boxing", sets: 2, workSeconds: 25, restSeconds: 35 },
      { exerciseId: "rodillazo-alterno", sets: 2, reps: 10, restSeconds: 35 },
      { exerciseId: "patada-frontal-alterna", sets: 2, reps: 8, restSeconds: 35 },
    ],
  },
  {
    id: "muaythai-express",
    name: "Muay Thai Express (10 min)",
    bodyParts: ["muay-thai"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Combo rápido de golpes y rodillazos para los días con poco tiempo.",
    blocks: [
      { exerciseId: "shadow-boxing", sets: 3, workSeconds: 25, restSeconds: 25 },
      { exerciseId: "rodillazo-alterno", sets: 3, reps: 14, restSeconds: 25 },
      { exerciseId: "patada-circular-alterna", sets: 3, reps: 10, restSeconds: 25 },
    ],
  },
  {
    id: "muaythai-core-avanzado",
    name: "Muay Thai — Core y Cadera",
    bodyParts: ["muay-thai", "core"],
    difficulty: "avanzado",
    equipment: ["ninguno"],
    description: "El core y la rotación de cadera detrás de cada golpe y patada.",
    blocks: [
      { exerciseId: "muay-thai-clinch-knees", sets: 4, reps: 18, restSeconds: 30 },
      { exerciseId: "russian-twist-kb", sets: 3, reps: 20, restSeconds: 30 },
      { exerciseId: "patada-circular-alterna", sets: 3, reps: 14, restSeconds: 30 },
      { exerciseId: "rodillazo-salto", sets: 3, reps: 10, restSeconds: 30 },
    ],
  },

  // ---------- MÁS PIERNAS ----------
  {
    id: "piernas-express-kb",
    name: "Piernas Express con Kettlebell (10 min)",
    bodyParts: ["piernas"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Circuito corto de piernas con kettlebell para no saltarte el día.",
    blocks: [
      { exerciseId: "sentadilla-goblet", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "peso-muerto-kb", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "zancada-kb", sets: 2, reps: 10, restSeconds: 30 },
    ],
  },
  {
    id: "piernas-isometrico-intermedio",
    name: "Piernas Isométrico",
    bodyParts: ["piernas"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Sostenes largos para construir resistencia muscular en piernas.",
    blocks: [
      { exerciseId: "wall-sit", sets: 4, workSeconds: 35, restSeconds: 35 },
      { exerciseId: "sumo-isometrico", sets: 3, workSeconds: 30, restSeconds: 35 },
      { exerciseId: "calf-raise", sets: 3, reps: 20, restSeconds: 30 },
    ],
  },
  {
    id: "piernas-gluteo-avanzado-2",
    name: "Piernas y Glúteo — Segunda Ronda",
    bodyParts: ["piernas"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Otra combinación distinta enfocada en glúteo, para no repetir siempre igual.",
    blocks: [
      { exerciseId: "puente-gluteo-kb", sets: 4, reps: 18, restSeconds: 30 },
      { exerciseId: "peso-muerto-una-pierna-kb", sets: 4, reps: 10, restSeconds: 35 },
      { exerciseId: "sentadilla-sumo-kb", sets: 4, reps: 15, restSeconds: 30 },
      { exerciseId: "zancada-lateral", sets: 3, reps: 12, restSeconds: 30 },
    ],
  },
  {
    id: "piernas-extremo-2",
    name: "Piernas Extremo — Segunda Ronda",
    bodyParts: ["piernas"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Otro circuito brutal de piernas, distinto al original.",
    blocks: [
      { exerciseId: "sentadilla-sumo-kb", sets: 5, reps: 18, restSeconds: 20 },
      { exerciseId: "salto-unilateral", sets: 4, reps: 8, restSeconds: 30 },
      { exerciseId: "step-up-kb", sets: 5, reps: 14, restSeconds: 25 },
      { exerciseId: "sentadilla-bulgara", sets: 4, reps: 12, restSeconds: 30 },
      { exerciseId: "wall-sit", sets: 3, workSeconds: 45, restSeconds: 25 },
    ],
  },

  // ---------- MÁS ESPALDA ----------
  {
    id: "espalda-express-2",
    name: "Espalda Express con Kettlebell (10 min)",
    bodyParts: ["espalda"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Remo y peso muerto rápido cuando el tiempo apremia.",
    blocks: [
      { exerciseId: "remo-kb-doble", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "peso-muerto-kb-espalda", sets: 3, reps: 12, restSeconds: 30 },
    ],
  },
  {
    id: "espalda-isometrico-intermedio",
    name: "Espalda Postural",
    bodyParts: ["espalda"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Trabajo isométrico para mejorar la postura de espalda alta y baja.",
    blocks: [
      { exerciseId: "pull-apart-imaginario", sets: 4, reps: 15, restSeconds: 25 },
      { exerciseId: "extension-espalda", sets: 3, reps: 15, restSeconds: 30 },
      { exerciseId: "superman-hold", sets: 3, workSeconds: 25, restSeconds: 30 },
    ],
  },
  {
    id: "espalda-avanzado-2",
    name: "Espalda — Segunda Ronda",
    bodyParts: ["espalda"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Otra combinación de tirón, distinta a la sesión original avanzada.",
    blocks: [
      { exerciseId: "remo-kb-una-mano", sets: 4, reps: 14, restSeconds: 30 },
      { exerciseId: "good-morning-kb", sets: 4, reps: 14, restSeconds: 30 },
      { exerciseId: "renegade-row-kb", sets: 3, reps: 10, restSeconds: 30 },
      { exerciseId: "kb-swing-una-mano", sets: 3, reps: 16, restSeconds: 30 },
    ],
  },

  // ---------- MÁS PECHO ----------
  {
    id: "pecho-isometrico-intermedio",
    name: "Pecho Isométrico",
    bodyParts: ["pecho"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Sostenes a media flexión para construir fuerza de pecho y tríceps.",
    blocks: [
      { exerciseId: "flexion-isometrica", sets: 4, workSeconds: 20, restSeconds: 35 },
      { exerciseId: "flexion-rodillas", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "plancha", sets: 3, workSeconds: 30, restSeconds: 30 },
    ],
  },
  {
    id: "pecho-avanzado-2",
    name: "Pecho — Segunda Ronda",
    bodyParts: ["pecho"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Otra combinación de empuje, distinta a la sesión avanzada original.",
    blocks: [
      { exerciseId: "flexion-declinada", sets: 4, reps: 14, restSeconds: 30 },
      { exerciseId: "press-pecho-kb", sets: 4, reps: 12, restSeconds: 30 },
      { exerciseId: "flexion-explosiva", sets: 3, reps: 8, restSeconds: 35 },
      { exerciseId: "pullover-kb", sets: 3, reps: 14, restSeconds: 30 },
    ],
  },
  {
    id: "pecho-express-2",
    name: "Pecho Express con Kettlebell (10 min)",
    bodyParts: ["pecho"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Press y flexiones rápido para no saltarte el día de pecho.",
    blocks: [
      { exerciseId: "press-pecho-kb", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "flexion-estandar", sets: 3, reps: 12, restSeconds: 30 },
    ],
  },

  // ---------- MÁS BRAZOS ----------
  {
    id: "brazos-extremo-2",
    name: "Brazos — Segunda Ronda Extremo",
    bodyParts: ["brazos"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Otra combinación brutal de brazos, distinta a la original.",
    blocks: [
      { exerciseId: "curl-martillo-kb", sets: 5, reps: 16, restSeconds: 20 },
      { exerciseId: "triceps-extension-kb", sets: 5, reps: 16, restSeconds: 20 },
      { exerciseId: "elevacion-lateral-kb", sets: 4, reps: 15, restSeconds: 20 },
      { exerciseId: "fondos-triceps", sets: 4, reps: 15, restSeconds: 20 },
    ],
  },
  {
    id: "brazos-express-2",
    name: "Brazos Express Sin Equipo (8 min)",
    bodyParts: ["brazos"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Otra variante rápida de brazos que no necesita kettlebell.",
    blocks: [
      { exerciseId: "fondos-triceps", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "plancha-arriba-abajo", sets: 2, reps: 10, restSeconds: 30 },
    ],
  },
  {
    id: "brazos-isometrico-intermedio",
    name: "Brazos y Hombro Isométrico",
    bodyParts: ["brazos"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Sostenes y movilidad para hombro y brazo, sin cargar peso.",
    blocks: [
      { exerciseId: "arm-circles", sets: 3, workSeconds: 25, restSeconds: 25 },
      { exerciseId: "plancha-arriba-abajo", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "fondos-triceps", sets: 3, reps: 14, restSeconds: 30 },
    ],
  },

  // ---------- MÁS FULL BODY / CARDIO ----------
  {
    id: "fullbody-fuerza-intermedio",
    name: "Full Body Fuerza",
    bodyParts: ["full-body"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Menos cardio, más fuerza pura de cuerpo completo.",
    blocks: [
      { exerciseId: "sentadilla-goblet", sets: 4, reps: 14, restSeconds: 35 },
      { exerciseId: "remo-kb-una-mano", sets: 4, reps: 12, restSeconds: 35 },
      { exerciseId: "press-pecho-kb", sets: 3, reps: 12, restSeconds: 35 },
      { exerciseId: "peso-muerto-kb", sets: 3, reps: 12, restSeconds: 35 },
    ],
  },
  {
    id: "fullbody-avanzado-2",
    name: "Full Body — Segunda Ronda",
    bodyParts: ["full-body"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Otra combinación de potencia y fuerza, distinta a las anteriores.",
    blocks: [
      { exerciseId: "kb-clean", sets: 4, reps: 10, restSeconds: 30 },
      { exerciseId: "farmer-carry-kb", sets: 3, workSeconds: 30, restSeconds: 30 },
      { exerciseId: "flexion-explosiva", sets: 3, reps: 8, restSeconds: 30 },
      { exerciseId: "oso-crawl", sets: 3, workSeconds: 25, restSeconds: 30 },
    ],
  },
  {
    id: "hiit-extremo-3",
    name: "HIIT Total — Tercera Ronda",
    bodyParts: ["cardio", "full-body"],
    difficulty: "extremo",
    equipment: ["ninguno"],
    description: "Circuito de HIIT sin kettlebell, para variar cuando no lo tengas a mano.",
    blocks: [
      { exerciseId: "burpee", sets: 5, workSeconds: 30, restSeconds: 20 },
      { exerciseId: "sprint-lateral", sets: 5, workSeconds: 25, restSeconds: 20 },
      { exerciseId: "salto-lateral-continuo", sets: 4, workSeconds: 25, restSeconds: 20 },
      { exerciseId: "mountain-climber", sets: 4, workSeconds: 30, restSeconds: 20 },
    ],
  },
  {
    id: "hiit-piernas-intermedio",
    name: "HIIT de Piernas Suave",
    bodyParts: ["cardio", "piernas"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Cardio de piernas con impacto moderado, ritmo intermedio.",
    blocks: [
      { exerciseId: "high-knees", sets: 4, workSeconds: 25, restSeconds: 25 },
      { exerciseId: "skater-jump", sets: 3, workSeconds: 20, restSeconds: 30 },
      { exerciseId: "sprint-lateral", sets: 3, workSeconds: 20, restSeconds: 30 },
    ],
  },

  // ---------- MÁS CORE EXPRESS (8 MIN, ROTAN COMO AÑADIDO DIARIO) ----------
  {
    id: "core-express-plancha",
    name: "Core Express — Plancha (8 min)",
    bodyParts: ["core"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Solo variantes de plancha, para estabilidad rápida.",
    blocks: [
      { exerciseId: "plancha", sets: 3, workSeconds: 25, restSeconds: 30 },
      { exerciseId: "plancha-lateral", sets: 2, workSeconds: 20, restSeconds: 30 },
      { exerciseId: "plancha-toques-hombro", sets: 2, reps: 14, restSeconds: 30 },
    ],
  },
  {
    id: "core-express-rotacion",
    name: "Core Express — Rotación (8 min)",
    bodyParts: ["core"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Movimiento rotacional para oblicuos, rápido y sin equipo.",
    blocks: [
      { exerciseId: "abdominal-bicicleta", sets: 3, reps: 16, restSeconds: 30 },
      { exerciseId: "sit-up", sets: 2, reps: 12, restSeconds: 30 },
      { exerciseId: "plancha-toques-hombro", sets: 2, reps: 12, restSeconds: 30 },
    ],
  },
  {
    id: "core-express-piernas",
    name: "Core Express — Abdomen Bajo (8 min)",
    bodyParts: ["core"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Elevaciones de pierna para la zona baja del abdomen.",
    blocks: [
      { exerciseId: "elevacion-piernas", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "v-ups", sets: 2, reps: 12, restSeconds: 30 },
      { exerciseId: "dead-bug", sets: 2, reps: 10, restSeconds: 25 },
    ],
  },
  {
    id: "core-express-isometrico",
    name: "Core Express — Isométrico (8 min)",
    bodyParts: ["core"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Solo sostenes, sin repeticiones dinámicas.",
    blocks: [
      { exerciseId: "plancha", sets: 3, workSeconds: 30, restSeconds: 30 },
      { exerciseId: "hollow-hold", sets: 2, workSeconds: 20, restSeconds: 30 },
      { exerciseId: "plancha-lateral", sets: 2, workSeconds: 25, restSeconds: 30 },
    ],
  },
  {
    id: "core-express-explosivo",
    name: "Core Express — Explosivo (8 min)",
    bodyParts: ["core"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Ritmo alto: core con componente cardio, no solo fuerza.",
    blocks: [
      { exerciseId: "mountain-climber", sets: 3, workSeconds: 25, restSeconds: 25 },
      { exerciseId: "plank-jack", sets: 2, workSeconds: 20, restSeconds: 25 },
      { exerciseId: "v-ups", sets: 2, reps: 12, restSeconds: 25 },
    ],
  },
  {
    id: "core-express-equilibrio",
    name: "Core Express — Equilibrio (8 min)",
    bodyParts: ["core"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Control y estabilidad antirrotación, ritmo tranquilo.",
    blocks: [
      { exerciseId: "dead-bug", sets: 3, reps: 10, restSeconds: 30 },
      { exerciseId: "elevacion-piernas", sets: 2, reps: 12, restSeconds: 30 },
      { exerciseId: "plancha-lateral", sets: 2, workSeconds: 20, restSeconds: 30 },
    ],
  },

  // ---------- MUCHA MÁS VARIEDAD GENERAL ----------
  {
    id: "piernas-tercera-ronda",
    name: "Piernas — Tercera Ronda",
    bodyParts: ["piernas"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Otra combinación distinta de piernas para no repetir siempre igual.",
    blocks: [
      { exerciseId: "sentadilla-goblet", sets: 4, reps: 15, restSeconds: 30 },
      { exerciseId: "step-up-kb", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "peso-muerto-una-pierna-kb", sets: 3, reps: 10, restSeconds: 35 },
    ],
  },
  {
    id: "piernas-movilidad-intermedio",
    name: "Piernas — Movilidad y Activación",
    bodyParts: ["piernas"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Movilidad de cadera antes de entrenar piernas con más carga.",
    blocks: [
      { exerciseId: "movilidad-cadera-90-90", sets: 2, reps: 8, restSeconds: 25 },
      { exerciseId: "circulos-cadera", sets: 2, workSeconds: 20, restSeconds: 20 },
      { exerciseId: "sentadilla-bw", sets: 3, reps: 15, restSeconds: 30 },
    ],
  },
  {
    id: "piernas-extremo-3",
    name: "Piernas Extremo — Tercera Ronda",
    bodyParts: ["piernas"],
    difficulty: "extremo",
    equipment: ["ninguno"],
    description: "Todo explosivo, sin kettlebell, para variar el estímulo.",
    blocks: [
      { exerciseId: "sentadilla-salto", sets: 5, workSeconds: 25, restSeconds: 20 },
      { exerciseId: "salto-unilateral", sets: 4, reps: 8, restSeconds: 30 },
      { exerciseId: "salto-lateral-continuo", sets: 4, workSeconds: 25, restSeconds: 20 },
      { exerciseId: "wall-sit", sets: 3, workSeconds: 40, restSeconds: 25 },
    ],
  },
  {
    id: "espalda-tercera-ronda",
    name: "Espalda — Tercera Ronda",
    bodyParts: ["espalda"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Otra combinación de tirón, distinta a las anteriores.",
    blocks: [
      { exerciseId: "remo-kb-doble", sets: 4, reps: 14, restSeconds: 30 },
      { exerciseId: "peso-muerto-kb", sets: 3, reps: 12, restSeconds: 35 },
      { exerciseId: "superman", sets: 3, reps: 15, restSeconds: 30 },
    ],
  },
  {
    id: "espalda-extremo-2",
    name: "Espalda Extremo — Segunda Ronda",
    bodyParts: ["espalda"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Otro circuito brutal de espalda, distinto al original.",
    blocks: [
      { exerciseId: "remo-kb-una-mano", sets: 5, reps: 16, restSeconds: 20 },
      { exerciseId: "kb-swing-una-mano", sets: 5, reps: 20, restSeconds: 20 },
      { exerciseId: "renegade-row-kb", sets: 4, reps: 12, restSeconds: 25 },
      { exerciseId: "good-morning-kb", sets: 4, reps: 15, restSeconds: 25 },
    ],
  },
  {
    id: "pecho-tercera-ronda",
    name: "Pecho — Tercera Ronda",
    bodyParts: ["pecho"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Otra combinación de flexiones, sin repetir siempre las mismas.",
    blocks: [
      { exerciseId: "flexion-amplia", sets: 4, reps: 12, restSeconds: 30 },
      { exerciseId: "flexion-declinada", sets: 3, reps: 10, restSeconds: 30 },
      { exerciseId: "plancha-desplazamiento", sets: 3, reps: 8, restSeconds: 30 },
    ],
  },
  {
    id: "pecho-extremo-2",
    name: "Pecho Extremo — Segunda Ronda",
    bodyParts: ["pecho"],
    difficulty: "extremo",
    equipment: ["ninguno"],
    description: "Alto volumen de flexiones sin kettlebell, para variar.",
    blocks: [
      { exerciseId: "flexion-estandar", sets: 5, reps: 18, restSeconds: 20 },
      { exerciseId: "flexion-diamante", sets: 5, reps: 12, restSeconds: 20 },
      { exerciseId: "flexion-explosiva", sets: 4, reps: 8, restSeconds: 25 },
      { exerciseId: "plancha-arriba-abajo", sets: 3, reps: 12, restSeconds: 25 },
    ],
  },
  {
    id: "core-avanzado-2",
    name: "Core de Acero — Segunda Ronda",
    bodyParts: ["core"],
    difficulty: "avanzado",
    equipment: ["ninguno"],
    description: "Otro circuito exigente de core, distinto al original.",
    blocks: [
      { exerciseId: "hollow-hold", sets: 4, workSeconds: 30, restSeconds: 25 },
      { exerciseId: "v-ups", sets: 4, reps: 16, restSeconds: 25 },
      { exerciseId: "plancha-desplazamiento", sets: 3, reps: 10, restSeconds: 25 },
      { exerciseId: "mountain-climber", sets: 3, workSeconds: 30, restSeconds: 25 },
    ],
  },
  {
    id: "core-extremo-2",
    name: "Core Extremo — Segunda Ronda",
    bodyParts: ["core"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Otra sesión brutal de abdomen, con kettlebell para variar la carga.",
    blocks: [
      { exerciseId: "russian-twist-kb", sets: 5, reps: 26, restSeconds: 20 },
      { exerciseId: "kb-halo", sets: 4, reps: 12, restSeconds: 20 },
      { exerciseId: "elevacion-piernas", sets: 4, reps: 18, restSeconds: 20 },
      { exerciseId: "hollow-hold", sets: 3, workSeconds: 35, restSeconds: 25 },
    ],
  },
  {
    id: "brazos-tercera-ronda",
    name: "Brazos — Tercera Ronda",
    bodyParts: ["brazos"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Otra combinación de brazos, distinta a las anteriores.",
    blocks: [
      { exerciseId: "curl-biceps-kb", sets: 4, reps: 14, restSeconds: 30 },
      { exerciseId: "triceps-extension-kb", sets: 3, reps: 14, restSeconds: 30 },
      { exerciseId: "elevacion-lateral-kb", sets: 3, reps: 12, restSeconds: 30 },
    ],
  },
  {
    id: "brazos-avanzado-2",
    name: "Brazos de Acero — Segunda Ronda",
    bodyParts: ["brazos"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Otra combinación exigente de brazos, distinta a la original.",
    blocks: [
      { exerciseId: "press-hombro-kb", sets: 4, reps: 14, restSeconds: 25 },
      { exerciseId: "curl-martillo-kb", sets: 4, reps: 15, restSeconds: 25 },
      { exerciseId: "fondos-triceps", sets: 4, reps: 15, restSeconds: 25 },
      { exerciseId: "elevacion-lateral-kb", sets: 3, reps: 14, restSeconds: 25 },
    ],
  },
  {
    id: "fullbody-tercera-ronda",
    name: "Full Body — Tercera Ronda",
    bodyParts: ["full-body"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Otra combinación de cuerpo completo, distinta a las anteriores.",
    blocks: [
      { exerciseId: "kb-clean-and-press", sets: 4, reps: 10, restSeconds: 35 },
      { exerciseId: "sentadilla-sumo-kb", sets: 3, reps: 14, restSeconds: 30 },
      { exerciseId: "renegade-row-kb", sets: 3, reps: 10, restSeconds: 30 },
    ],
  },
  {
    id: "fullbody-extremo-2",
    name: "Full Body Extremo — Segunda Ronda",
    bodyParts: ["full-body"],
    difficulty: "extremo",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Otro desafío completo de fuerza y potencia, distinto al original.",
    blocks: [
      { exerciseId: "kb-thruster", sets: 5, reps: 15, restSeconds: 20 },
      { exerciseId: "kb-snatch", sets: 5, reps: 10, restSeconds: 25 },
      { exerciseId: "burpee", sets: 5, reps: 15, restSeconds: 20 },
      { exerciseId: "farmer-carry-kb", sets: 3, workSeconds: 35, restSeconds: 25 },
    ],
  },
  {
    id: "fullbody-sin-equipo-intermedio",
    name: "Full Body Sin Equipo",
    bodyParts: ["full-body"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Cuerpo completo sin kettlebell, para los días sin equipo a mano.",
    blocks: [
      { exerciseId: "burpee-sin-salto", sets: 4, reps: 10, restSeconds: 30 },
      { exerciseId: "flexion-estandar", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "sentadilla-salto", sets: 3, workSeconds: 20, restSeconds: 30 },
      { exerciseId: "oso-crawl", sets: 3, workSeconds: 20, restSeconds: 30 },
    ],
  },
  {
    id: "hiit-tercera-ronda",
    name: "HIIT — Tercera Ronda",
    bodyParts: ["cardio"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Otra combinación de cardio, distinta a las anteriores.",
    blocks: [
      { exerciseId: "jumping-jacks", sets: 4, workSeconds: 25, restSeconds: 25 },
      { exerciseId: "mountain-climber", sets: 3, workSeconds: 25, restSeconds: 25 },
      { exerciseId: "plank-jack", sets: 3, workSeconds: 20, restSeconds: 25 },
    ],
  },
  {
    id: "hiit-avanzado-2",
    name: "HIIT Intenso — Segunda Ronda",
    bodyParts: ["cardio"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Otro circuito intenso de cardio, con kettlebell para variar.",
    blocks: [
      { exerciseId: "kb-swing-cardio", sets: 5, workSeconds: 30, restSeconds: 20 },
      { exerciseId: "skater-jump", sets: 4, workSeconds: 25, restSeconds: 20 },
      { exerciseId: "sprint-lateral", sets: 4, workSeconds: 20, restSeconds: 20 },
    ],
  },
  {
    id: "hiit-express-2",
    name: "HIIT Express — Segunda Ronda (8 min)",
    bodyParts: ["cardio"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Otra opción rápida de cardio, distinta a la express original.",
    blocks: [
      { exerciseId: "sprint-en-lugar", sets: 3, workSeconds: 20, restSeconds: 20 },
      { exerciseId: "salto-lateral-continuo", sets: 3, workSeconds: 20, restSeconds: 20 },
      { exerciseId: "mountain-climber", sets: 3, workSeconds: 20, restSeconds: 20 },
    ],
  },
  {
    id: "portero-cardio-intermedio",
    name: "Portero — Resistencia Cardiovascular",
    bodyParts: ["portero", "cardio"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Resistencia general para aguantar los 90 minutos bajo los tres palos.",
    blocks: [
      { exerciseId: "portero-pies-rapidos", sets: 4, workSeconds: 20, restSeconds: 25 },
      { exerciseId: "high-knees", sets: 3, workSeconds: 25, restSeconds: 25 },
      { exerciseId: "portero-reaccion-lateral", sets: 3, reps: 10, restSeconds: 25 },
    ],
  },
  {
    id: "muaythai-piernas-intermedio",
    name: "Muay Thai — Resistencia de Piernas",
    bodyParts: ["muay-thai", "piernas"],
    difficulty: "intermedio",
    equipment: ["ninguno"],
    description: "Resistencia de piernas para aguantar rondas completas de patadas.",
    blocks: [
      { exerciseId: "patada-frontal-alterna", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "high-knees", sets: 3, workSeconds: 20, restSeconds: 25 },
      { exerciseId: "sentadilla-bw", sets: 3, reps: 15, restSeconds: 30 },
    ],
  },
  {
    id: "movilidad-espalda-principiante",
    name: "Movilidad de Espalda",
    bodyParts: ["espalda"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Rango de movimiento para espalda alta y columna, sin cargar.",
    blocks: [
      { exerciseId: "gato-camello", sets: 3, reps: 10, restSeconds: 25 },
      { exerciseId: "rotacion-toracica", sets: 2, reps: 8, restSeconds: 25 },
      { exerciseId: "perro-pajaro", sets: 2, reps: 10, restSeconds: 30 },
    ],
  },
  {
    id: "movilidad-pecho-hombro-principiante",
    name: "Movilidad de Pecho y Hombro",
    bodyParts: ["pecho", "brazos"],
    difficulty: "principiante",
    equipment: ["ninguno"],
    description: "Preparación de hombro antes de entrenar empuje con más intensidad.",
    blocks: [
      { exerciseId: "arm-circles", sets: 2, workSeconds: 20, restSeconds: 25 },
      { exerciseId: "pull-apart-imaginario", sets: 2, reps: 15, restSeconds: 25 },
      { exerciseId: "flexion-rodillas", sets: 2, reps: 10, restSeconds: 30 },
    ],
  },
  {
    id: "piernas-kb-avanzado-2",
    name: "Piernas con Kettlebell — Segunda Ronda",
    bodyParts: ["piernas"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Otra combinación intensa de piernas con kettlebell.",
    blocks: [
      { exerciseId: "sentadilla-goblet", sets: 5, reps: 16, restSeconds: 25 },
      { exerciseId: "zancada-kb", sets: 4, reps: 12, restSeconds: 30 },
      { exerciseId: "peso-muerto-kb", sets: 4, reps: 12, restSeconds: 30 },
      { exerciseId: "calf-raise", sets: 3, reps: 20, restSeconds: 25 },
    ],
  },
  {
    id: "core-kb-express",
    name: "Core con Kettlebell Express (10 min)",
    bodyParts: ["core"],
    difficulty: "intermedio",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Rotación y estabilidad con kettlebell en poco tiempo.",
    blocks: [
      { exerciseId: "russian-twist-kb", sets: 3, reps: 20, restSeconds: 30 },
      { exerciseId: "kb-halo", sets: 2, reps: 10, restSeconds: 30 },
    ],
  },
  {
    id: "espalda-piernas-avanzado",
    name: "Peso Muerto y Tirón",
    bodyParts: ["espalda", "piernas"],
    difficulty: "avanzado",
    equipment: ["kb-10kg", "kb-15lb", "kb-10lb"],
    description: "Combina el patrón de bisagra de cadera con tirón de espalda.",
    blocks: [
      { exerciseId: "peso-muerto-kb-espalda", sets: 4, reps: 12, restSeconds: 35 },
      { exerciseId: "remo-kb-una-mano", sets: 4, reps: 12, restSeconds: 30 },
      { exerciseId: "good-morning-kb", sets: 3, reps: 12, restSeconds: 30 },
      { exerciseId: "swing-kb", sets: 3, reps: 18, restSeconds: 30 },
    ],
  },
];

export function getSessionById(id: string): Session | undefined {
  return SESSIONS.find((s) => s.id === id);
}
